name: flutter_module
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <2.15.9"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  json_model: ^1.0.0
  build_runner: 2.1.7
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.flutter_module
    iosBundleIdentifier: com.example.flutterModule
