name: my_flutter
description: A new flutter module project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.14.4<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
  cupertino_icons: ^1.0.2
  json_annotation: 4.4.0
  flutter_staggered_grid_view: ^0.6.0
  cached_network_image: ^3.2.0
#  url_launcher: ^6.0.17
  random_color: 1.0.6-nullsafety
  get: ^4.6.1
  provider: ^6.0.2
  flutter_plugin:
    path: ./flutter_plugin
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  json_model: ^1.0.0
  build_runner: 2.1.7
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true
  assets:
    - test/datas/item_list.json
  module:
    androidX: true
    androidPackage: com.example.my_flutter
    iosBundleIdentifier: com.example.myFlutter
