# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


# 混编 https://docs.flutter.dev/development/add-to-app/ios/project-setup

flutter_application_path = '../my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


target 'MyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  install_all_flutter_pods(flutter_application_path)

  # Pods for MyApp

end
